### Regressão Logística

#### É um algoritmo de classificação  para variaveis categóricas (0 e 1).
#### Com ele não só preveremos qual a classe de cada valor, mas também mediremos a probabilidade de um caso pertencer a uma classe especifica

In [14]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [15]:
df = pd.read_csv('data/iris.data.csv')

In [16]:
df.head()

sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [17]:
x = np.asarray(df[['sepal length','sepal width','petal length','petal width']])
y = np.asarray(df[['class']])

#### Tratamento do Y

In [18]:
pos = 0
for i in y:
    if (i == 'Iris-setosa'):
        y[pos] = '0'
    if(i == 'Iris-virginica'):
        y[pos]= '1'
    if(i == 'Iris-versicolor'):
        y[pos]= '2'
    pos+=1

In [19]:
x[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [20]:
y[:5]

array([['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0']], dtype=object)

### Normaliza o dataset

In [21]:
from sklearn import preprocessing
x=preprocessing.StandardScaler().fit(x).transform(x.astype(float))
x[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

### Divisão de treino e teste

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=4)
print ('Set de Treino:', X_train.shape,  y_train.shape)
print ('Set de Teste:', X_test.shape,  y_test.shape)

Set de Treino: (120, 4) (120, 1)
Set de Teste: (30, 4) (30, 1)


### Modelamento

##### Regularização: é uma técnica usada para resolver o problema de overfitting
##### O parâmetro C indica: inverse da força de regularização que deve ser um float positivo. Valores menores especificam uma regularização mais forte
#### solver = 'liblinear' é recomendado para datasets pequenos. Enquanto 'sag' e 'saga' são mais rápidos para os grandes. 
####           para problemas multiclasse 'newton-cg', 'sag', 'saga' e 'lbfgs' lidam com a perda multinomial.

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='sag').fit(X_train,y_train)
LR

C:\Users\LauraDamacenodeAlmei\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\LauraDamacenodeAlmei\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='sag',
          tol=0.0001, verbose=0, warm_start=False)

In [24]:
yhat = LR.predict(X_test)
yhat

array(['1', '0', '1', '1', '1', '2', '2', '0', '0', '2', '0', '0', '0',
       '2', '2', '0', '2', '0', '0', '1', '0', '1', '2', '0', '0', '0',
       '2', '0', '0', '2'], dtype=object)

#### .predict_proba(): retorna estimativas para todas as classes, ordenadas pelo rótulos. [x,y,z]
#### A primeira coluna é a probabilidade de ser da classe X. A segunda coluna da classe Y e a terceira coluna é da classe Z

In [25]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.12766374, 0.4676096 , 0.40472666],
       [0.51942736, 0.19793283, 0.28263982],
       [0.09698772, 0.505873  , 0.39713928],
       [0.08631604, 0.53994896, 0.37373499],
       [0.1050133 , 0.5034359 , 0.3915508 ],
       [0.21332158, 0.38033264, 0.40634578],
       [0.17360404, 0.4005481 , 0.42584786],
       [0.55917592, 0.18317535, 0.25764873],
       [0.53852828, 0.19095933, 0.27051238],
       [0.17460478, 0.40960625, 0.41578897],
       [0.47678674, 0.16469485, 0.3585184 ],
       [0.53151659, 0.15619974, 0.31228367],
       [0.50014591, 0.14815094, 0.35170314],
       [0.20919375, 0.383266  , 0.40754026],
       [0.15128477, 0.40828509, 0.44043014],
       [0.50331418, 0.15334961, 0.34333621],
       [0.24282692, 0.25914876, 0.49802433],
       [0.52376133, 0.14742703, 0.32881164],
       [0.52196948, 0.16227834, 0.31575217],
       [0.15549053, 0.42398001, 0.42052946],
       [0.51246184, 0.15601551, 0.33152264],
       [0.14673487, 0.49574666, 0.35751846],
       [0.

### Evolução

#### Indice de Jaccard
##### Podemos definir jaccard como o tamanho da interseção dividida pelo tamanho da união de dois conjuntos de rótulos.
##### Se todo o conjunto de rótulos previstos para uma amostra corresponder estritamente ao conjunto real de rótulos, a precisão do subconjunto será 1.0; caso contrário, é 0.0.

In [26]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yhat)

0.8666666666666667

In [27]:
from sklearn import metrics

In [30]:
print("Precisão em porcentagem do teste: ", metrics.accuracy_score(y_test, yhat)*100)
print('F1 score: ',metrics.f1_score(y_test, yhat,average=None))

Precisão em porcentagem do teste:  86.66666666666667
F1 score:  [0.96774194 0.8        0.71428571]
